# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module HelloWorld5
  # HelloWorldResponse Model.
  class HelloWorldResponse < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :xample

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :message

    # A mapping from model property names to API property names.
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash['xample'] = 'xample'
        @_hash['message'] = 'message'
      end
      @_hash
    end

    def initialize(xample = nil,
                   message = nil)
      @xample = xample
      @message = message
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      xample = hash['xample']
      message = hash['message']

      # Create object from extracted values.
      HelloWorldResponse.new(xample,
                             message)
    end
  end
end
