# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module HelloWorld5
  #  hello_world_5 client class.
  class HelloWorld5Client
    # Singleton access to helloworld controller.
    # @return [HelloworldController] Returns the controller instance.
    def helloworld
      HelloworldController.instance
    end

    # Returns the configuration class for easy access.
    # @return [Configuration] Returns the actual configuration class.
    def config
      Configuration
    end
  end
end
