# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module HelloWorld5
  # HelloworldController
  class HelloworldController < BaseController
    @instance = HelloworldController.new

    class << self
      attr_accessor :instance
    end

    def instance
      self.class.instance
    end

    # TODO: type endpoint description here
    # @return HelloWorldResponse response from the API call
    def get_helloworld
      # Prepare query url.
      _query_builder = Configuration.base_uri.dup
      _query_builder << '/helloworld'
      _query_url = APIHelper.clean_url _query_builder

      # Prepare headers.
      _headers = {
        'accept' => 'application/json'
      }

      # Prepare and execute HttpRequest.
      _request = @http_client.get(
        _query_url,
        headers: _headers
      )
      _context = execute_request(_request)
      validate_response(_context)

      # Return appropriate response type.
      decoded = APIHelper.json_deserialize(_context.response.raw_body)
      HelloWorldResponse.from_hash(decoded)
    end
  end
end
